package com.example.jeremy.pcmap;

/**
 * Created by ladislavsteffko on 3/7/17.
 */

// Class that enumerates names of places in PC
public enum PlaceName {
    SRC,
    Santorini,
    SunshineMarket,
    Subway,
    Starbucks,
    Rubios,
    Lemongrass,
    PriceTheater,
    PandaExpress,
    ChaseBank,
    BurgerKing,
    BombayCoast,
    TapiocaExpress,
    PerksCoffee,
    Bookstore,
    Jamba,
    Zone,
    BoxOffice,
    RoundTablePizza,
    CommuterKitchen,
    UCSDPolice,
    ACCB,
    ACTA,
    Lounge,
    StudyRooms,
    ComputerLab,
    Lockers,
    SeedSprout,

    EsenciaDeSaborSuPan,
    Y_Mas,
    VivaPops,

    Shogun,
    SunGodLounge,
    Arcade,
    TheLoft,
    ZanzibarCafe,
    CrossCulturalCenter,
    ERCRoom,
    MarshalRoom,
    RevelleRoom,
    MuirRoom,
    InterTribalRC,
    StudOrg2,
    GreenRoom,
    LactationRoom,
    BallroomWestA,
    BallroomWestB,
    BallroomEast,
    RedShoeRoom,
    BearRoom,
    Kaplan,
    GreenTableRoom,
    Salon101,
    ArtSpace,
    Communidad,
    DanceStudio,
    GameRoom,
    SPACE,

    StudOrg3,
    WarrenRoom,
    UniCenAdmin,
    OneStop,
    SixthRoom,
    ASVolCon,
    ASGraphStudio,
    AlumniAffairs,
    StudLifeBusiOps,
    UniCenEveSer,
    CenCommLead,
    CenStudInvol,

    Forum,
    GovCham,
    GradStudAssoc,
    UniEveOff,
    SenateCham,
    AVCStudLife,
    AssocStud,
    StudLeadCham,

    PCTheaterRestroom,
    PandaRestroom,
    PerksRestroom,
    CommuterRestroom,
    RoundTablePizzaRestroom,
    SalonRestroom,
    WestBallroomRestroom,
    SGLRestroom,
    WarrenRestroom,
    OneStopRestroom,
    RecepRestroom,

    PCTheaterHydro,
    BurgerKingHydro,
    YHWHydro,
    ArcadeHydro,
    OneStopHydro,
    RecepHydro,

    Entr2,
    Entr3,
    BookEntr,

    SGLCorner,
    SGLEast,
    CCCCorner,
    CCCWest,
    OutStairCorner,
    East2Entr,

    IntersectionWest,
    IntersectionEast,

    StairFlr1W,
    StairFlr2W,

    StairFlr1SE,
    StairFlr2SE,

    StairFlr1E,
    StairFlr2E,
    StairFlr3E,

    InStairsPCE1,
    InStairsPCE2,
    InStairsSLBO2,
    InStairsSLBO3,
    InStairsDesk3,
    InStairsDesk4,

    OutElev1,
    OutElev2,
    OutElev3,
    TritonStatueElev1,
    TritonStatueElev2,

    InElev1,
    InElev2,
    InElev3,
    InElev4,
    BookstoreElev1,
    BookstoreElev2,
    BookstoreElev3

}
