package com.example.jeremy.pcmap;

/**
 * Created by ladislavsteffko on 3/7/17.
 */

// Class that enumerates names of places in PC
public enum PlaceName {
    SRC,
    Santorini,
    SunshineMarket,
    Subway,
    Starbucks,
    Rubios,
    Lemongrass,
    PriceTheater,
    PandaExpress,
    ChaseBank,
    BurgerKing,
    BombayCoast,
    TapiocaExpress,
    PostalCenter,
    PerksCoffee,
    Bookstore,
    Jamba,
    Zone,
    BoxOffice,
    RoundTablePizza,
    CommuterKitchen,
    UCSDPolice,
    ACCB,
    ACTA,
    Lounge,
    StudyRooms,
    ComputerLab,
    Lockers,

    Shogun,
    SunGodLounge,
    Arcade,
    TheLoft,
    ZanzibarCafe,
    CrossCulturalCenter,
    ERCRoom,
    MarshalRoom,
    RevelleRoom,
    MuirRoom,
    InterTribalRC,
    StudOrg2,
    GreenRoom,
    LactationRoom,
    BallroomWestA,
    BallroomWestB,
    BallroomEast,
    RedShoeRoom,
    BearRoom,
    Kaplan,
    GreenTableRoom,
    Saloon101,
    ArtSpace,
    Communidad,
    DanceStudio,
    GameRoom,

    StudOrg3,
    WarrenRoom,
    UniCenAdmin,
    OneStop,
    SixthRoom,
    ASVolCon,
    ASGraphStudio,
    AlumniAffairs,
    StudLifeBusiOps,
    UniCenEveSer,
    CenCommLead,
    CenStudInvol,

    Forum,
    GovCham,
    GradStudAssoc,
    UniEveOff,
    SenateCham,
    AVCStudLife,
    AssocStud,
    StudLeadCham,

    IntersectionWest,
    IntersectionEast
}
